title: "Tutoriales SENCE-IEB"
description: "Colección de tutoriales del curso SENCE-IEB"
url: "https://ricardosegovia.github.io"
baseurl: "/sence_ieb"   # IMPORTANTE para sitio de proyecto
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
collections:
  tutorials:
    output: true
    permalink: /tutorials/:title/
defaults:
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial
      nav: tutorials
plugins:
  - jekyll-feed
